# Generated by Django 3.1.7 on 2021-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
