# Generated by Django 3.1.7 on 2021-05-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
