# Generated by Django 3.1.7 on 2021-05-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0005_data_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_manage.area'),
        ),
    ]
